### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by DeeJaVu** [jordanbardsley7/laravel-admin#4]
Hello, what is the difference between AdminMiddleware, and AdminGuestMiddleware ?

**Comment by jordanbardsley7** [comment]
@DeeJaVu Looks like it was just a middleware to redirect the user if they were already authenticated, it would be the equivalent of [this](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/RedirectIfAuthenticated.php). Looking back the name of the class is a bit misleading.
